### PR TITLE
Qt 4.8 fix

### PR DESCRIPTION
**Pull request by jeremy-brenner**
Just a compiler directive to include getopt.h when qt version > 4.8.  Fixes specrunner compile issues on newer qt versions:

specrunner.cpp: In function ‘int main(int, char*_)’:
specrunner.cpp:37:39: error: ‘getopt’ was not declared in this scope
specrunner.cpp:43:20: error: ‘optarg’ was not declared in this scope
specrunner.cpp:48:7: error: ‘optind’ was not declared in this scope
specrunner.cpp:61:16: error: ‘optind’ was not declared in this scope
make: *_\* [specrunner.o] Error 1

If you could merge it would be superfantastic.

### CODE REVIEW

**Comment by jeremy-brenner** [comment]
P.S. This doesn't break builds on qt 4.7
