### ISSUE TITLE
Cannot Compile in Ruby 1.9.3p194 

### ISSUE THREAD

**Issue by skamansam** [johnbintz/jasmine-headless-webkit#156]
I can't compile for ruby 1.9.3-p194. This is a duplicate of another closed ticket (which I can't reopen). Here are my commands and output:
# > gem install jasmine-headless-webkit -v '0.8.4' > ~/bundlejas.txt

ERROR:  Error installing jasmine-headless-webkit:
        ERROR: Failed to build gem native extension.

```
    /home/sam/.rvm/rubies/ruby-1.9.3-p194-fast/bin/ruby extconf.rb
```

make: **\* No rule to make target `clean'.  Stop.
Qmake version: 1.07a (Qt 3.3.8b)
Qmake is free software from Trolltech ASA.
/home/sam/.rvm/gems/ruby-1.9.3-p194-fast/gems/jasmine-headless-webkit-0.8.4/lib/qt/qmake.rb:68:in`qt_version_of': undefined method `[]' for nil:NilClass (NoMethodError)
        from /home/sam/.rvm/gems/ruby-1.9.3-p194-fast/gems/jasmine-headless-webkit-0.8.4/lib/qt/qmake.rb:75:in`block in best_qmake'
        from /home/sam/.rvm/gems/ruby-1.9.3-p194-fast/gems/jasmine-headless-webkit-0.8.4/lib/qt/qmake.rb:72:in `collect'
        from /home/sam/.rvm/gems/ruby-1.9.3-p194-fast/gems/jasmine-headless-webkit-0.8.4/lib/qt/qmake.rb:72:in`best_qmake'
        from /home/sam/.rvm/gems/ruby-1.9.3-p194-fast/gems/jasmine-headless-webkit-0.8.4/lib/qt/qmake.rb:49:in `path'
        from /home/sam/.rvm/gems/ruby-1.9.3-p194-fast/gems/jasmine-headless-webkit-0.8.4/lib/qt/qmake.rb:12:in`installed?'
        from /home/sam/.rvm/gems/ruby-1.9.3-p194-fast/gems/jasmine-headless-webkit-0.8.4/lib/qt/qmake.rb:124:in `check_qmake!'
        from /home/sam/.rvm/gems/ruby-1.9.3-p194-fast/gems/jasmine-headless-webkit-0.8.4/lib/qt/qmake.rb:38:in`make!'
        from extconf.rb:8:in `<main>'

Gem files will remain installed in /home/sam/.rvm/gems/ruby-1.9.3-p194-fast/gems/jasmine-headless-webkit-0.8.4 for inspection.
Results logged to /home/sam/.rvm/gems/ruby-1.9.3-p194-fast/gems/jasmine-headless-webkit-0.8.4/ext/jasmine-webkit-specrunner/gem_make.out
# > echo $QMAKE

/usr/bin/qmake-qt4
# > qmake -v

Qmake version: 1.07a (Qt 3.3.8b)
Qmake is free software from Trolltech ASA.
# > qmake-qt4 -v

QMake version 2.01a
Using Qt version 4.8.2 in /usr/lib64
# > qt4-qmake -v

QMake version 2.01a
Using Qt version 4.8.2 in /usr/lib64

This says my Qmake version is for Qt3, but I am using an alias (it is the same regardless of an alias), as well as the QMAKE environment variable to set the Qt path. qmake points to Qt3, while qmake-qt4 points to qt4. I also created another symlink for qt4-qmake which points to qmake-qt4. Perhaps using the QMAKE env setting may make this work a little better - without having to install and maintain a system (alternatives, which may not be available to all linux users).  I am using Fedora 16, with no ruby/rails RPMs installed. My compilation worked flawlessly for 1.9.3p125:
# > ruby -v

ruby 1.9.3p125 (2012-02-16 revision 34643) [x86_64-linux]
# > bundle list jasmine-headless-webkit

/home/sam/.rvm/gems/ruby-1.9.3-p125-perf/gems/jasmine-headless-webkit-0.8.4

**Comment by aamerik-teladoc** [comment]
yum remove qt3-devel solved my problem  with this

**Comment by sdmcraft** [comment]
Thanks a ton!! yum remove qt3-devel solved my problem as well.

**Comment by YongwenZhao** [comment]
:+1:
